# Generated by Django 3.2.16 on 2022-11-22 08:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20221121_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments_count',
            field=models.ManyToManyField(blank=True, related_name='blogpost_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
